version: "3"
services:
  flarum:
    image: mondedie/flarum:stable
    env_file:
      - .env
    volumes:
      - ${APP_CODE_PATH_HOST}/assets:/flarum/app/public/assets
      - ${APP_CODE_PATH_HOST}/extensions:/flarum/app/extensions
      - ${APP_CODE_PATH_HOST}/nginx:/etc/nginx/conf.d
    ports:
      - ${FLARUM_HTTP_PORT}:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql/db:/var/lib/mysql
volumes:
        {}
